"""提示词模块"""
from prompts.base_prompts import (
    BASE_SYSTEM_PROMPT,
    REQUIREMENT_ANALYSIS_PROMPT,
    TEST_GENERATION_PROMPT
)

__all__ = [
    'BASE_SYSTEM_PROMPT',
    'REQUIREMENT_ANALYSIS_PROMPT',
    'TEST_GENERATION_PROMPT'
]
